// resources/js/vue/crm/pages/Home.vue
<script setup lang="ts">
    import AppLayout from '@/vue/default/layout/AppLayout.vue';
    import { Head } from '@inertiajs/vue3';

    const doThis = () => {
        console.log('haha');
    };
</script>

<template>
    <Head title="Home"></Head>
    <AppLayout>
        <div class="flex flex-col gap-2">
            Vue CRM App
            <button class="border" @click="doThis">Click Me</button>
        </div>
    </AppLayout>
</template>

// resources/js/react/Crm/pages/Home.tsx
import AppLayout from "@/react/default/layout/AppLayout";
import { Head } from "@inertiajs/react";

export default function Page() {

    const doThis = () => {
        console.log('haha');
    }

    return (
        <>
            <Head title="React Home"></Head>
            <AppLayout>
                <div className="flex flex-col items-start p-4">
                    <h2 className="text-xl">React CRM Home</h2>
                    <button onClick={doThis} className="border p-2 bg-blue-50">Click me</button>
                </div>
            </AppLayout>
        </>
    )
}
